# Generated by Django 3.0.8 on 2020-07-26 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='car_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
                ('manufature_year', models.IntegerField(max_length=100)),
            ],
        ),
    ]
